vad:
  pre_unit : 4
  thr_up : 8
  thr_down : 4
  thr_energy : 0.00
---
dsp:
  epsiBF : 0.0001 # 1e-3 ~ 1e-6, low -> weak
  epsiSVE : 0.0001 # 1e-3  ~ 1e-6, low -> weak
---
gd:
  thr : 6
---
m2 :
  method : "ratio"
  ratio : 0.3